sudo: required
language: dart
dart:
  - stable
services:
  - docker
before_install:
  - docker build -t test .
script:
  - docker run -it test 
after_success:
  - bash <(curl -s https://codecov.io/bash)