sudo: required
services:
  - docker
before_install:
  - docker build -t test .
script:
  - docker run -t test pub run test
  # - docker run -t test pub run -c test -p content-shell
after_success:
  - docker run -t test /bin/sh -c "pub run dart_codecov_generator --report-on=lib/ --no-html --verbose test/engine && bash codecov_report"