sudo: required
services:
  - docker
before_install:
  - docker build -t test .
script:
  - docker run -t test pub run test
  # - docker run -t test pub run -c test -p content-shell // world is not ready yet
# after_success:
  # - docker run --privileged -t test bash -cx ../tools/codecov -R /root/application -s /root/application