sudo: required
services:
  - docker
before_install:
  - docker build -t test .
script:
  - docker run -it test pub run test
  # - docker run -it test pub run -c test -p content-shell // world is not ready yet