name: whisper
version: 0.1.0
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
description: 'Engine of real time content management'
homepage: https://github.com
environment:
  sdk: '>=1.18.1 <2.0.0'
dependencies:
  browser: '^0.10.0+2'
  mime: '^0.9.3'
  path: '^1.3.9'

  uuid: '^0.5.3'

  socket_system:
    version: '^0.9.0'
    git: 'https://github.com/WhisperEngine/SocketSystem.git'
  
  event_system:
    version: '^1.2.0'
    git: 'https://github.com/WhisperEngine/EventSystem.git'

  # microservices
  pages:
    git: 'https://github.com/WhisperEngine/Pages.git'

dev_dependencies:
  test: '^0.12.15+3'
  coverage: '^0.8.0+1'
  dart_codecov_generator: '^0.4.0'
dependency_overrides:
  logging: '^0.11.0'
transformers:
  - test/pub_serve:
      $include: test/**_test{.*,}.dart