name: whisper
version: 0.1.0
author: Vostrikov Vitaliy <rasart.pro@gmail.com>
description: 'Engine of real time content management'
homepage: https://github.com
environment:
  sdk: '>=1.18.1 <2.0.0'
dependencies:
  avalanche_events: '^0.10.7'
  browser: '^0.10.0+2'
  mime: '^0.9.3'
  path: '^1.3.9'
  polymer: '^1.0.0-rc.18'
  polymer_elements: '^1.0.0-rc.9'
  web_socket_channel: '^1.0.4'
dev_dependencies:
  test: '^0.12.15+3'
transformers:
  - polymer:
      entry_points: web/index.html
  - test/pub_serve:
      $include: test/**_test{.*,}.dart 